[package]
name = "tokio_select_in_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
mini-redis = "0.4.1"
futures = "0.3.30"
bytes ="1"